server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
  datasource:
    url: jdbc:h2:file:~/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
