server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
  queue: gamification_multiplication_queue
  anything:
    routing-key: multiplication.*

multiplicationHost: http://localhost:8000/
